# Kata 15 - Range Extraction

https://www.codewars.com/kata/51ba717bb08c1cd60f00002f/train/python

### Instructions
A format for expressing an ordered list of integers is to use a comma separated list of either 

- individual integers
- or a range of integers denoted by the starting integer separated from the end integer in the range by a dash, '-'. The range includes all integers in the interval including both endpoints. It is not considered a range unless it spans at least 3 numbers. For example "12,13,15-17"

Complete the solution so that it takes a list of integers in increasing order and returns a correctly formatted string in the range format.

### Examples
- solution([-6, -3, -2, -1, 0, 1, 3, 4, 5, 7, 8, 9, 10, 11, 14, 15, 17, 18, 19, 20])
- returns "-6,-3-1,3-5,7-11,14,15,17-20"


In [2]:
import numpy as np

def solution(args):
    pass
    # your code here

In [63]:
original = np.array([-6, -3, -2, -1, 0, 1, 3, 4, 5, 7, 8, 9, 10, 11, 14, 15, 17, 18, 19, 20])
display(original)
complete = np.array(list(range(min(original),max(original)+1,1)))
display(complete)

array([-6, -3, -2, -1,  0,  1,  3,  4,  5,  7,  8,  9, 10, 11, 14, 15, 17,
       18, 19, 20])

array([-6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [64]:
new = []
for ind,val in enumerate(complete):
    if val in original:
        new.append(val)
    else:
        new.append(None)
new = np.array(new)
display(new)

array([-6, None, None, -3, -2, -1, 0, 1, None, 3, 4, 5, None, 7, 8, 9, 10,
       11, None, None, 14, 15, None, 17, 18, 19, 20], dtype=object)

In [65]:
# display("original:", original)
# display("complete: ",complete)
# display("new: ",new)

In [108]:
p = [1,2,3]
p[4]

IndexError: list index out of range

In [113]:
# # current deve
# from  itertools import chain

# main = list()
# for i in range(len(new)):
#     if new[i] in chain(*main): 
#         pass
#     else:
#         if new[i] != None:
#             list_new = [new[i]]
#             print(list_new)
#             try:
#                 count = 0
#                 while count < len(new):
#                     if new[i+1+count] <= len(new):
#                         if new[i+1+count]==None:
#                             print("breaks here: ",new[i+1+count])
#                             main.append(list_new)
#                             break
#                         else:
#                             #print(new[i+1])
#                             list_new.append(new[i+1+count])
#                         count = count + 1
# #                 main.append(list_new)
#                 #print(list_new)
#             except: pass
# main

In [139]:
# unedited -- current deve
from  itertools import chain

main = list()
for i in range(len(new)):
    if new[i] in chain(*main): 
        pass
    else:
        if new[i] != None:
            list_new = [new[i]]
            try:
                count = 0
                while (count < len(new)) and (new[i+1+count]!=None): 
                        list_new.append(new[i+1+count])
                        count = count + 1
                main.append(list_new)
                print(list_new)
            except: pass
main

[-6]
[-3, -2, -1, 0, 1]
[3, 4, 5]
[7, 8, 9, 10, 11]
[14, 15]


[[-6], [-3, -2, -1, 0, 1], [3, 4, 5], [7, 8, 9, 10, 11], [14, 15]]

In [117]:
new[28]!=None

IndexError: index 28 is out of bounds for axis 0 with size 27

In [ ]:
####################Current Working Solution#########################3

In [125]:
# unedited -- current deve
from  itertools import chain

main = list()
for i in range(len(new)):
    if new[i] in chain(*main): 
        pass
    else:
        if new[i] != None:
            list_new = [new[i]]
            try:
                count = 0
                while (count < len(new)) and (new[i+1+count]!=None): 
                        list_new.append(new[i+1+count])
                        count = count + 1
                main.append(list_new)
                print(list_new)
            except: pass
main

[-6]
[-3, -2, -1, 0, 1]
[3, 4, 5]
[7, 8, 9, 10, 11]
[14, 15]


[[-6], [-3, -2, -1, 0, 1], [3, 4, 5], [7, 8, 9, 10, 11], [14, 15]]

In [141]:
k = [2,3,4]
def str_list(k):
    '''takes a list and returns string formatting'''
    if len(k)<3:
        x = ','.join(str(x) for x in k)
        return(x)
    else:
        x = str(min(k))+"-" + str(max(k))
        return(x)
#str_list(k)
final = ''
for i in main:
    #print(str_list(i))
    final = final + str_list(i) + "," ############# need to fix this
final
#returns "-6,-3-1,3-5,7-11,14,15,17-20"

'-6,-3-1,3-5,7-11,14,15,'

# Resources



https://www.geeksforgeeks.org/python-check-if-element-exists-in-list-of-lists/

In [ ]:

# Python code to demonstrate
# finding whether element
# exists in listof list
from  itertools import chain
  
# initialising nested lists
ini_list = [[1, 2, 5, 10, 7], 
            [4, 3, 4, 3, 21],
            [45, 65, 8, 8, 9, 9]]
  
elem_to_find = 8
elem_to_find1 = 0
  
# element exists in listof listor not?
res1 = elem_to_find in chain(*ini_list)
res2 = elem_to_find1 in chain(*ini_list)
  
# printing result
print(str(res1), "\n", str(res2))